# =============================================================================
# Configuración de Tema del Template Customizer
# Este archivo se genera/actualiza automáticamente desde el panel de customización.
# Se commitea a git para que la configuración viaje con el proyecto.
# =============================================================================
theme:
  preset: lemonade
  custom_colors:
    primary: "#519903"
    secondary: "#e9e92f"
    success: "#519903"
    danger: "#e7515a"
    warning: "#e9e92f"
    info: "#2196f3"
layout:
  scheme: light
  menu: vertical
  style: full
  direction: ltr
  animation: animate__fadeIn
  navbar: navbar-sticky
  semidark: true
logo:
  text: Template Base
  image: "/assets/images/cuatropuntocero_logo_icon.PNG"
  show_image: true
